version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "java-app-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-2mzswssye9jw"
s3_prefix = "app-backend-java"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAqM"